name = "ONIONop"
uuid = "021020d5-7125-488f-a684-9e3366e41e56"
version = "0.1.0"
authors = ["Anton Oresten <antonoresten@gmail.com>", "Anton Smirnov <tonysmn97@gmail.com>"]

[workspace]
projects = ["test"]

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
ONIONopAMDGPUExt = "AMDGPU"
ONIONopCUDAExt = "CUDA"

[compat]
AMDGPU = "1.2.5, 2"
CUDA = "5"
ChainRulesCore = "1.25.1"
KernelAbstractions = "0.9.34"
LRUCache = "1.6.2"
Memoize = "0.4.4"
StaticArrays = "1.9.13"
